# -*- coding: utf-8 -*-
"""acquire_DSPI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MUWOHG5Z4TZxms7ELQd9UjX0BcQ1bB17
"""

import os
import requests
import hashlib

os.makedirs("data/raw", exist_ok=True)

DSPI_url = "https://fred.stlouisfed.org/graph/fredgraph.csv?bgcolor=%23ebf3fb&chart_type=line&drp=0&fo=open%20sans&graph_bgcolor=%23ffffff&height=450&mode=fred&recession_bars=on&txtcolor=%23444444&ts=12&tts=12&width=1320&nt=0&thu=0&trc=0&show_legend=yes&show_axis_titles=yes&show_tooltip=yes&id=DSPI&scale=left&cosd=1959-01-01&coed=2026-01-01&line_color=%230073e6&link_values=false&line_style=solid&mark_type=none&mw=3&lw=3&ost=-99999&oet=99999&mma=0&fml=a&fq=Monthly&fam=avg&fgst=lin&fgsnd=2020-02-01&line_index=1&transformation=lin&vintage_date=2026-04-05&revision_date=2026-04-05&nd=1959-01-01"
DSPI_filename = "data/raw/DSPI_raw.csv"

response = requests.get(DSPI_url)

with open(DSPI_filename, "wb") as f:
    f.write(response.content)

print("Saved DSPI dataset:", DSPI_filename)

def sha256(path):
    with open(path, "rb") as f:
        return hashlib.sha256(f.read()).hexdigest()

print("DSPI SHA-256:", sha256(DSPI_filename))

import pandas as pd

df = pd.read_csv(DSPI_filename)
df.head()

print("Shape:", df.shape)
print("Columns:", df.columns.tolist())
print("\nData types:")
print(df.dtypes)

print("Missing values:")
print(df.isna().sum())

print("\nDuplicate rows:", df.duplicated().sum())

df[df.columns[0]] = pd.to_datetime(df[df.columns[0]], errors="coerce")
df = df[(df["observation_date"] >= '2015-01-01') & (df["observation_date"] <= '2026-01-01')]
print("Date range:", df[df.columns[0]].min(), "to", df[df.columns[0]].max())

df.head()

os.makedirs("data/filtered_10yrs", exist_ok=True)
df.to_csv('data/filtered_10yrs/DSPI_filtered.csv', index = False)
